---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Preliminary steps
Before working with the data, I'm going to set some display options for this document and load some libraries.
```{r optschunkset}
library(knitr) # Adding this here makes RStudio's Knit HTML button work

# Need to check if this is necessary. From the forums
# https://class.coursera.org/repdata-036/forum/thread?thread_id=83
opts_chunk$set(echo = TRUE,
               message = FALSE, warning = FALSE,
               cache = FALSE#, # maybe make this true in the end?
               #cache.path = "cache/", 
               #fig.path = "figure/"
               )
```

```{r libraryload}
library(dplyr)
library(lubridate)
```

## Loading and preprocessing the data
```{r}
# Get the data, if needed.
if (!file.exists("activity.csv")) {
  if (!file.exists("activity.zip")) {
    url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
    destfile <- "activity.zip"
    download.file(url, destfile, method = "curl")
    downloadDate <- date()
  }
unzip(zipfile = "activity.zip")
}

# Missing values are correctly handled by default 'NA',
# but dates need will be forced to strings and then converted
# using dplyr and lubridate.
activity <- read.csv("activity.csv", stringsAsFactors = FALSE)
activity <- mutate(activity, date = ymd(date))

```


## What is mean total number of steps taken per day?
```{r}
# Get an atomic vector of daily steps, NAs removed
dailysteps <- activity %>% 
  group_by(date) %>% 
  summarise_each(funs(sum)) %>% 
  select(steps) %>% 
  unlist %>% 
  na.omit
```


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
